- name: Backup identity home
  ansible.builtin.archive:
    path: {{ item }}/products/identity_home
    dest: {{ item }}/products/identity_home_{{ hostname }}_{{ date }}_0904.tar.gz
    format: gz
  loop: {{ domain_base }}