- name: Apply WebLogic PSU Patch
  block:
    - name: Rollback Previous Patch
      command: |
        export ORACLE_HOME={{ item }}
        {{ item }}/OPatch/opatch rollback -id {{ patch_id }}
      loop: {{ oracle_home }}

    - name: Apply SPB
      command: |
        export ORACLE_HOME={{ item }}

        {{ item }}/{{ weblogic_patch_directory }}/WLS_SPB_12.2.1.4.240710/tools/spbat/generic/SPBAT 
        ./spbat.sh -phase apply -oracle.home {{ item }}
      loop: {{ oracle_home }}

    - name: Apply Patch
      command: {{ item }}/OPatch/opatch apply
      loop: {{ oracle_home }}

  rescue:
    - name: Rollback Curent Patch if error caught
      command: |
        export ORACLE_HOME={{ item }}
        {{ item }}/OPatch/opatch rollback -id {{ current_patch_id }}
      loop: {{ oracle_home }}