- name: Apply Java Patch
  block:
    - name: Move Old JDK
      command: "mv {{ java_home }}/jdk1.8 {{ java_home }}/jdk1.8_old"

    - name: Copy New JDK
      copy:
        src: "{{ upgrade_home }}/java/jdk1.8_{{ jdk_patch_number }}/jdk1.8.0_{{ jdk_patch_number }}"
        dest: "{{ java_home }}/jdk1.8"
        remote_src: yes

- name: Check Java Version
  block:
    - name: Set JAVA_HOME and PATH
      shell: |
        export JAVA_HOME={{ java_home }}/jdk1.8
        export PATH=$JAVA_HOME/bin:$PATH
        java -version
      register: java_version

    - name: Display Java Version
      debug:
        msg: "{{ java_version.stdout }}"
