- name: Prepare for WebLogic PSU Patch
  block:
    - name: Unzip WebLogic PSU Patch
      unarchive:
        src: {{ upgrade_home }}/{{ weblogic_patch_directory }}/{{ weblogic_patch_zip }}
        dest: {{ upgrade_home }}/{{ weblogic_patch_directory }}/
        remote_src: yes