- name: Start Node Manager
  ansible.builtin.shell: |
    nohup startNodeManager.sh &
  args:
    chdir: "{{ item }}/bin"
  loop: "{{ domain_home }}"

- name: Wait for Node Manager to Start
  shell: |
    while ! pgrep -f NodeManager > /dev/null; do sleep 5; done
    echo "Node Manager is up"

- name: Start WebLogic Admin Server
  command: "nohup {{ item }}/bin/startWebLogic.sh >> {{ item }}/servers/AdminServer/logs/AdminServer.out 2>&1 &"
  async: 300
  poll: 10
  loop: "{{ domain_home }}"

- name: Start WebLogic Admin Server
  ansible.builtin.shell: |
    nohup startWebLogic.sh >> {{ item }}/servers/AdminServer/logs/AdminServer.out 2>&1 &
    while ! grep -q 'Server startup complete' {{ domain_home }}/servers/AdminServer/logs/AdminServer.out; do sleep 5; done
    echo "Admin Server is up"
  args:
    chdir: "{{ item }}/bin"
  loop: "{{ domain_home }}"
