---
- hosts: all
  vars:
    - container_registry: "localhost/"
    - autonomous_database_tag: ""
    - weblogic_server_tag: ""
    - autonomous_database_wallet_password: "123456789aA123"
    - autonomous_admin_password: "123456789aA123"
    - weblogic_username: "hello"
    - weblogic_password: "123456789"
    - security_properties: |-
        username={{ weblogic_username }}
        password={{ weblogic_password }}
        JAVA_OPTIONS=-Dweblogic.StdoutDebugEnabled=true
  tasks:
    - name: Clean up running containers
      ansible.builtin.shell: |
        podman stop $(podman ps -q) || echo
        podman rm $(podman ps -aq) || echo
      become: true

    -


