---
- hosts: all
  vars:
    - container_registry: "container-registry.oracle.com"
    - container_registry_username: ""
    - container_registry_password: ""
    - container_registry_local: "localhost/"
    - autonomous_database_tag: ""
    - weblogic_server_tag: ""
    - autonomous_database_wallet_password: "123456789aA123"
    - autonomous_admin_password: "123456789aA123"
    - weblogic_username: "hello"
    - weblogic_password: "123456789"
    - github_username: ""
    - github_password: ""
  tasks:
    - name: Install needed packages on the remote machine
      become: yes
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
          - git
          - podman
        state: present

    - name: Install dependencies
      ansible.builtin.shell: |
        pip3 install ansible
        pip3 install ansible-core
      args:
        executable: /bin/bash

    - name: Clone a repo with separate git directory
      ansible.builtin.git:
        repo: https://github.com/oracleweboadb/oracle
        dest: /home/root/oracle
        version: main
        force: yes
      become: true

#    - name: Clone a repo with separate git directory
#      ansible.builtin.git:
#        repo: https://{{ github_username }}:{{ github_password }}@github.com/MTA-IT-Middleware-Platform-Technology/ordsapps
#        dest: /home/root/oracle
#        version: main
#        force: yes
#      environment:
#        http_proxy: nyc3.sme.zscaler.net:10560
#        https_proxy: nyc3.sme.zscaler.net:10560
#      become: true

    - name: Print ansible version and install containers.podman
      ansible.builtin.shell: |
        ansible --version
        ansible-galaxy collection list
        ansible-galaxy collection install containers.podman

      args:
        executable: /bin/bash
      become: true

    - name: Run ansible playbook
      ansible.builtin.shell: |
        cd /home/root/oracle
        git reset --hard
        
        ansible-playbook /home/root/oracle/ansible-main/build_and_deploy.yaml --extra-vars "container_registry={{ container_registry }} container_registry_username={{ container_registry_username }} container_registry_password={{ container_registry_password }} container_registry_local={{ container_registry_local }} autonomous_database_tag={{ autonomous_database_tag }} weblogic_server_tag={{ weblogic_server_tag }} autonomous_database_wallet_password={{ autonomous_database_wallet_password }} autonomous_admin_password={{ autonomous_admin_password }} weblogic_username={{ weblogic_username }} weblogic_password={{ weblogic_password }} github_username={{ github_username }} github_password={{ github_password }}"
      args:
        executable: /bin/bash
      become: true


