#- name: main
- hosts: all
  become: true
  gather_facts: true

  tasks:
    # JDK Patching tasks
    - name: Run prepare jdk patch tasks
      include_tasks: tasks/prepare_jdk.yaml

    - name: Run stop services tasks
      include_tasks: tasks/stop_services.yaml

    - name: Run jdk backup tasks
      include_tasks: tasks/backup_jdk.yaml

    - name: Run jdk patch
      include_tasks: tasks/patch_jdk.yaml

    # Weblogic Patching tasks
    - name: Run prepare weblogic patch tasks
      include_tasks: tasks/prepare_weblogic.yaml

    - name: Run weblogic backup tasks
      include_tasks: tasks/backup_weblogic.yaml

    - name: Run weblogic patch
      include_tasks: tasks/patch_weblogic.yaml

    - name: Run weblogic patch
      include_tasks: tasks/start_services.yaml