name: Build and deploy oad, weblogic servers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "build and deploy containers"
        run: |
          pip3 install awxkit
          
          cat > extra_vars.json << EOF
          {
            "container_registry_username": "${{ secrets.OR_USERNAME }}",
            "container_registry_password": "${{ secrets.OR_PASSWORD }}",
            "autonomous_database_tag": "${{ github.sha }}",
            "weblogic_server_tag": "${{ github.sha }}",
            "weblogic_username": "${{ secrets.WEBLOGIC_USERNAME }}",
            "weblogic_password": "${{ secrets.WEBLOGIC_PASSWORD }}",
            "autonomous_database_wallet_password": "${{ secrets.AUTONOMOUS_DATABASE_WALLET_PASSWORD }}",
            "autonomous_admin_password": "${{ secrets.AUTONOMOUS_ADMIN_PASSWORD }}"
          }
          EOF
          
          JSON_VAR=$(cat ./extra_vars.json | tr -d '\n' | tr -d '[:blank:]')
          echo "awx --conf.host ${{ secrets.AWX_URL }} --conf.username  ${{ secrets.AWX_USER }} --conf.password ${{ secrets.AWX_PASSWORD }} --extra_vars=$JSON_VAR job_templates launch 11"
          awx --conf.host ${{ secrets.AWX_URL }} --conf.username  ${{ secrets.AWX_USER }} --conf.password ${{ secrets.AWX_PASSWORD }} job_templates launch 11 --extra_vars=$JSON_VAR        
            
            

