name: Build and deploy oad, weblogic servers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "build contaienrs"
        run: |
          pip3 install awxkit
          awx --help
          
          cat > extra_vars.json << EOF
          {
            "container_registry_username": "${{ secrets.OR_USERNAME }}",
            "container_registry_password": "${{ secrets.OR_PASSWORD }}",
            "autonomous_database_tag": "${{ github.sha }}",
            "weblogic_server_tag": "${{ github.sha }}",
            "weblogic_username": "${{ secrets.WEBLOGIC_USERNAME }}",
            "weblogic_password": "${{ secrets.WEBLOGIC_PASSWORD }}"
          }
          EOF
          
          awx --conf.host ${{ secrets.AWX_URL }} --conf.username ${{ secrets.AWX_USER }} --conf.password ${{ secrets.AWX_PASSWORD }} --extra-vars extra_vars.json job_templates launch 9         

      - name: "deploy contaienrs"
        run: |
          pip3 install awxkit
          
          cat > extra_vars.json << EOF
          {
            "autonomous_database_tag": "${{ github.sha }}",
            "weblogic_server_tag": "${{ github.sha }}",
            "weblogic_username": "${{ secrets.WEBLOGIC_USERNAME }}",
            "weblogic_password": "${{ secrets.WEBLOGIC_PASSWORD }}"
            "autonomous_database_wallet_password": "${{ secrets.AUTONOMOUS_DATABASE_WALLET_PASSWORD }}",
            "autonomous_admin_password: "${{ secrets.AUTONOMOUS_ADMIN_PASSWORD }}"
          }
          EOF
          
          awx --conf.host ${{ secrets.AWX_URL }} --conf.username  ${{ secrets.AWX_USER }} --conf.password ${{ secrets.AWX_PASSWORD }} --extra-vars extra_vars.json job_templates launch 10        
            
            

