name: Build and deploy oad, weblogic servers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: opt-nc/tower-deploy-action@v1.3.4
        with:
          extravars_template_filename: ""
          tower_user: ${{ secrets.AWX_USER }}
          tower_password: ${{ secrets.AWX_PASSWORD }}
          tower_url: ${{ secrets.AWX_URL }}
          tower_template_id: "build-containers"
          vars: |
            {
              "container_registry_username": "${{ secrets.OR_USERNAME }}",
              "container_registry_password": "${{ secrets.OR_PASSWORD }}",
              "autonomous_database_tag": "${{ github.sha }}",
              "weblogic_server_tag": "${{ github.sha }}",
              "weblogic_username": "${{ secrets.WEBLOGIC_USERNAME }}",
              "weblogic_password": "${{ secrets.WEBLOGIC_PASSWORD }}"
            }

      - uses: opt-nc/tower-deploy-action@v1.3.4
        with:
          extravars_template_filename: ""
          tower_user: ${{ secrets.AWX_USER }}
          tower_password: ${{ secrets.AWX_PASSWORD }}
          tower_url: ${{ secrets.AWX_URL }}
          tower_template_id: "deploy-containers"
          vars: |
            {
              "autonomous_database_tag": "${{ github.sha }}",
              "weblogic_server_tag": "${{ github.sha }}",
              "weblogic_username": "${{ secrets.WEBLOGIC_USERNAME }}",
              "weblogic_password": "${{ secrets.WEBLOGIC_PASSWORD }}"
              "autonomous_database_wallet_password": "${{ secrets.AUTONOMOUS_DATABASE_WALLET_PASSWORD }}",
              "autonomous_admin_password: "${{ secrets.AUTONOMOUS_ADMIN_PASSWORD }}"
            }

